configure:
  languages:
    javascript: true
    go: true
    protobuf: true
  plugins:
    - .aspect/cli/rules_cc.star
plugins:
    - name: fix-visibility
      from: github.com/aspect-build/plugin-fix-visibility
      version: v0.1.0