name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    env:
      # Required for rules_swift
      # https://github.com/bazelbuild/rules_swift#3-additional-configuration-linux-only
      CC: clang

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install the Swift toolchain
      - uses: cgrindel/gha_install_swift_on_ubuntu@v1
        with:
          swift_release_tag: "swift-5.8.1-RELEASE"
          ubuntu_version: "22.04"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: |
            "~/.cache/bazel"
            "~/.cache/bazel-repo"
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'MODULE.bazel') }}
          restore-keys: bazel-cache-

      # Make the PATH available to build actions so that the Swift toolchain is discoverable.
      - name: Update local.bazelrc with Linux Flags
        shell: bash
        run: |
          cat >> "local.bazelrc" <<EOF
          # Need to expose the PATH so that the Swift toolchain can be found
          build --action_env=PATH
          EOF

      - name: bazel test //...
        env:
          # Bazelisk will download bazel to here, ensure it is cached between runs.
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        working-directory: ${{ matrix.folder }}
        run: |
          bazel test //...
          bazel test //:manual_tests

  macos_test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3.1"
      - uses: cgrindel/gha_set_up_bazel@v1
        with:
          repo_name: codelabs
      - name: Execute Bazel Tests
        shell: bash
        run: |
          bazel test //... 
          bazel test //:manual_tests

  test:
    runs-on: ubuntu-latest
    needs:
      - macos_test
      - ubuntu_test
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


